#coding: utf8

RESULT_SUCCEED                      = 0
RESULT_FAILED                       = 1

RESULT_FAILED_ACCOUNT_INVALID       = 2
RESULT_FAILED_ACCOUNT_OR_PASSWORD_INVALID      = 3
RESULT_FAILED_NO_LOGIN              = 4
RESULT_FAILED_NAME_EXISTED          = 5
RESULT_FAILED_ACCOUNT_EMPTY         = 7
RESULT_FAILED_ACCOUNT_DISABLED      = 8
RESULT_FAILED_ACCOUNT_LENGTH_EQUALS_ZERO       = 9
RESULT_FAILED_ACCOUNT_LENGTH       = 10

RESULT_FAILED_CODE_FILL = 11
RESULT_FAILED_CODE_EXPIRED = 12
RESULT_FAILED_TODAY_SIGNED = 13

RESULT_FAILED_SMS_EMPTY = -1100
RESULT_FAILED_SMS_SEND_FAILED = -1104
RESULT_FAILED_SMS_NOT_EQUALS = -1102
RESULT_FAILED_SMS_EXITS = -1103

RESULT_FAILED_SHOP_DIAMOND          = -200
RESULT_FAILED_SHOP                  = -201

RESULT_FAILED_INVALID_USER          = -10000
RESULT_FAILED_INVALID_GOLD          = -10001
RESULT_FAILED_INVALID_TABLE         = -10002
RESULT_FAILED_ALREADY_READY         = -10003
RESULT_FAILED_ALREADY_START         = -10004
RESULT_FAILED_NOT_START             = -10005
RESULT_FAILED_INVALID_TURN          = -10006
RESULT_FAILED_SHOW_HAND             = -10007
RESULT_FAILED_NO_ENOUGH_GOLD        = -10008
RESULT_FAILED_INVALID_GAMBLER       = -10009
RESULT_FAILED_INVALID_GOLD          = -10010
RESULT_FAILED_INVALID_ROUND         = -10011
RESULT_FAILED_MORE_GAMBLERS         = -10012
RESULT_FAILED_ALREADY_SIT           = -10013
