# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trade.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import constant_pb2
import struct_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='trade.proto',
  package='cardgame',
  serialized_pb=_b('\n\x0btrade.proto\x12\x08\x63\x61rdgame\x1a\x0e\x63onstant.proto\x1a\x0cstruct.proto\"\x1e\n\x0cQueryShopReq\"\x0e\n\x03\x44\x45\x46\x12\x07\n\x02ID\x10\xb8\x17\"B\n\rQueryShopResp\x12!\n\x05items\x18\x01 \x03(\x0b\x32\x12.cardgame.ShopItem\"\x0e\n\x03\x44\x45\x46\x12\x07\n\x02ID\x10\xb9\x17\"A\n\nBuyItemReq\x12\x14\n\x0cshop_item_id\x18\x01 \x02(\x05\x12\r\n\x05\x63ount\x18\x02 \x02(\x05\"\x0e\n\x03\x44\x45\x46\x12\x07\n\x02ID\x10\xba\x17\"?\n\x0b\x42uyItemResp\x12 \n\x06result\x18\x01 \x01(\x0b\x32\x10.cardgame.Result\"\x0e\n\x03\x44\x45\x46\x12\x07\n\x02ID\x10\xbb\x17\"Q\n\rQueryTradeReq\x12\x0c\n\x04page\x18\x01 \x02(\x05\x12\x11\n\tpage_size\x18\x02 \x02(\x05\x12\x0f\n\x07\x63\x61n_buy\x18\x03 \x02(\x08\"\x0e\n\x03\x44\x45\x46\x12\x07\n\x02ID\x10\xbc\x17\"P\n\x0eQueryTradeResp\x12\x1f\n\x06trades\x18\x01 \x03(\x0b\x32\x0f.cardgame.Trade\x12\r\n\x05total\x18\x02 \x02(\x05\"\x0e\n\x03\x44\x45\x46\x12\x07\n\x02ID\x10\xbd\x17\"/\n\x0b\x42uyTradeReq\x12\x10\n\x08trade_id\x18\x01 \x02(\x05\"\x0e\n\x03\x44\x45\x46\x12\x07\n\x02ID\x10\xbe\x17\"@\n\x0c\x42uyTradeResp\x12 \n\x06result\x18\x01 \x01(\x0b\x32\x10.cardgame.Result\"\x0e\n\x03\x44\x45\x46\x12\x07\n\x02ID\x10\xbf\x17\"<\n\x0bSellGoldReq\x12\x0c\n\x04gold\x18\x01 \x02(\x05\x12\x0f\n\x07\x64iamond\x18\x02 \x02(\x05\"\x0e\n\x03\x44\x45\x46\x12\x07\n\x02ID\x10\xc0\x17\"@\n\x0cSellGoldResp\x12 \n\x06result\x18\x01 \x01(\x0b\x32\x10.cardgame.Result\"\x0e\n\x03\x44\x45\x46\x12\x07\n\x02ID\x10\xc1\x17\".\n\nOutGoldReq\x12\x10\n\x08trade_id\x18\x01 \x02(\x05\"\x0e\n\x03\x44\x45\x46\x12\x07\n\x02ID\x10\xc2\x17\"?\n\x0bOutGoldResp\x12 \n\x06result\x18\x01 \x01(\x0b\x32\x10.cardgame.Result\"\x0e\n\x03\x44\x45\x46\x12\x07\n\x02ID\x10\xc3\x17\x42#\n\x18\x63om.zhili.cardgame.protoB\x05TradeH\x03')
  ,
  dependencies=[constant_pb2.DESCRIPTOR,struct_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_QUERYSHOPREQ_DEF = _descriptor.EnumDescriptor(
  name='DEF',
  full_name='cardgame.QueryShopReq.DEF',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ID', index=0, number=3000,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=71,
  serialized_end=85,
)
_sym_db.RegisterEnumDescriptor(_QUERYSHOPREQ_DEF)

_QUERYSHOPRESP_DEF = _descriptor.EnumDescriptor(
  name='DEF',
  full_name='cardgame.QueryShopResp.DEF',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ID', index=0, number=3001,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=139,
  serialized_end=153,
)
_sym_db.RegisterEnumDescriptor(_QUERYSHOPRESP_DEF)

_BUYITEMREQ_DEF = _descriptor.EnumDescriptor(
  name='DEF',
  full_name='cardgame.BuyItemReq.DEF',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ID', index=0, number=3002,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=206,
  serialized_end=220,
)
_sym_db.RegisterEnumDescriptor(_BUYITEMREQ_DEF)

_BUYITEMRESP_DEF = _descriptor.EnumDescriptor(
  name='DEF',
  full_name='cardgame.BuyItemResp.DEF',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ID', index=0, number=3003,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=271,
  serialized_end=285,
)
_sym_db.RegisterEnumDescriptor(_BUYITEMRESP_DEF)

_QUERYTRADEREQ_DEF = _descriptor.EnumDescriptor(
  name='DEF',
  full_name='cardgame.QueryTradeReq.DEF',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ID', index=0, number=3004,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=354,
  serialized_end=368,
)
_sym_db.RegisterEnumDescriptor(_QUERYTRADEREQ_DEF)

_QUERYTRADERESP_DEF = _descriptor.EnumDescriptor(
  name='DEF',
  full_name='cardgame.QueryTradeResp.DEF',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ID', index=0, number=3005,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=436,
  serialized_end=450,
)
_sym_db.RegisterEnumDescriptor(_QUERYTRADERESP_DEF)

_BUYTRADEREQ_DEF = _descriptor.EnumDescriptor(
  name='DEF',
  full_name='cardgame.BuyTradeReq.DEF',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ID', index=0, number=3006,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=485,
  serialized_end=499,
)
_sym_db.RegisterEnumDescriptor(_BUYTRADEREQ_DEF)

_BUYTRADERESP_DEF = _descriptor.EnumDescriptor(
  name='DEF',
  full_name='cardgame.BuyTradeResp.DEF',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ID', index=0, number=3007,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=551,
  serialized_end=565,
)
_sym_db.RegisterEnumDescriptor(_BUYTRADERESP_DEF)

_SELLGOLDREQ_DEF = _descriptor.EnumDescriptor(
  name='DEF',
  full_name='cardgame.SellGoldReq.DEF',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ID', index=0, number=3008,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=613,
  serialized_end=627,
)
_sym_db.RegisterEnumDescriptor(_SELLGOLDREQ_DEF)

_SELLGOLDRESP_DEF = _descriptor.EnumDescriptor(
  name='DEF',
  full_name='cardgame.SellGoldResp.DEF',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ID', index=0, number=3009,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=679,
  serialized_end=693,
)
_sym_db.RegisterEnumDescriptor(_SELLGOLDRESP_DEF)

_OUTGOLDREQ_DEF = _descriptor.EnumDescriptor(
  name='DEF',
  full_name='cardgame.OutGoldReq.DEF',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ID', index=0, number=3010,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=727,
  serialized_end=741,
)
_sym_db.RegisterEnumDescriptor(_OUTGOLDREQ_DEF)

_OUTGOLDRESP_DEF = _descriptor.EnumDescriptor(
  name='DEF',
  full_name='cardgame.OutGoldResp.DEF',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ID', index=0, number=3011,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=792,
  serialized_end=806,
)
_sym_db.RegisterEnumDescriptor(_OUTGOLDRESP_DEF)


_QUERYSHOPREQ = _descriptor.Descriptor(
  name='QueryShopReq',
  full_name='cardgame.QueryShopReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _QUERYSHOPREQ_DEF,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=85,
)


_QUERYSHOPRESP = _descriptor.Descriptor(
  name='QueryShopResp',
  full_name='cardgame.QueryShopResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='cardgame.QueryShopResp.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _QUERYSHOPRESP_DEF,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=153,
)


_BUYITEMREQ = _descriptor.Descriptor(
  name='BuyItemReq',
  full_name='cardgame.BuyItemReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='shop_item_id', full_name='cardgame.BuyItemReq.shop_item_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count', full_name='cardgame.BuyItemReq.count', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _BUYITEMREQ_DEF,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=220,
)


_BUYITEMRESP = _descriptor.Descriptor(
  name='BuyItemResp',
  full_name='cardgame.BuyItemResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='cardgame.BuyItemResp.result', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _BUYITEMRESP_DEF,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=222,
  serialized_end=285,
)


_QUERYTRADEREQ = _descriptor.Descriptor(
  name='QueryTradeReq',
  full_name='cardgame.QueryTradeReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='page', full_name='cardgame.QueryTradeReq.page', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='page_size', full_name='cardgame.QueryTradeReq.page_size', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='can_buy', full_name='cardgame.QueryTradeReq.can_buy', index=2,
      number=3, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _QUERYTRADEREQ_DEF,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=287,
  serialized_end=368,
)


_QUERYTRADERESP = _descriptor.Descriptor(
  name='QueryTradeResp',
  full_name='cardgame.QueryTradeResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='trades', full_name='cardgame.QueryTradeResp.trades', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='total', full_name='cardgame.QueryTradeResp.total', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _QUERYTRADERESP_DEF,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=370,
  serialized_end=450,
)


_BUYTRADEREQ = _descriptor.Descriptor(
  name='BuyTradeReq',
  full_name='cardgame.BuyTradeReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='trade_id', full_name='cardgame.BuyTradeReq.trade_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _BUYTRADEREQ_DEF,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=452,
  serialized_end=499,
)


_BUYTRADERESP = _descriptor.Descriptor(
  name='BuyTradeResp',
  full_name='cardgame.BuyTradeResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='cardgame.BuyTradeResp.result', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _BUYTRADERESP_DEF,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=501,
  serialized_end=565,
)


_SELLGOLDREQ = _descriptor.Descriptor(
  name='SellGoldReq',
  full_name='cardgame.SellGoldReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gold', full_name='cardgame.SellGoldReq.gold', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='diamond', full_name='cardgame.SellGoldReq.diamond', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SELLGOLDREQ_DEF,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=567,
  serialized_end=627,
)


_SELLGOLDRESP = _descriptor.Descriptor(
  name='SellGoldResp',
  full_name='cardgame.SellGoldResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='cardgame.SellGoldResp.result', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SELLGOLDRESP_DEF,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=629,
  serialized_end=693,
)


_OUTGOLDREQ = _descriptor.Descriptor(
  name='OutGoldReq',
  full_name='cardgame.OutGoldReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='trade_id', full_name='cardgame.OutGoldReq.trade_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _OUTGOLDREQ_DEF,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=695,
  serialized_end=741,
)


_OUTGOLDRESP = _descriptor.Descriptor(
  name='OutGoldResp',
  full_name='cardgame.OutGoldResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='cardgame.OutGoldResp.result', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _OUTGOLDRESP_DEF,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=743,
  serialized_end=806,
)

_QUERYSHOPREQ_DEF.containing_type = _QUERYSHOPREQ
_QUERYSHOPRESP.fields_by_name['items'].message_type = struct_pb2._SHOPITEM
_QUERYSHOPRESP_DEF.containing_type = _QUERYSHOPRESP
_BUYITEMREQ_DEF.containing_type = _BUYITEMREQ
_BUYITEMRESP.fields_by_name['result'].message_type = struct_pb2._RESULT
_BUYITEMRESP_DEF.containing_type = _BUYITEMRESP
_QUERYTRADEREQ_DEF.containing_type = _QUERYTRADEREQ
_QUERYTRADERESP.fields_by_name['trades'].message_type = struct_pb2._TRADE
_QUERYTRADERESP_DEF.containing_type = _QUERYTRADERESP
_BUYTRADEREQ_DEF.containing_type = _BUYTRADEREQ
_BUYTRADERESP.fields_by_name['result'].message_type = struct_pb2._RESULT
_BUYTRADERESP_DEF.containing_type = _BUYTRADERESP
_SELLGOLDREQ_DEF.containing_type = _SELLGOLDREQ
_SELLGOLDRESP.fields_by_name['result'].message_type = struct_pb2._RESULT
_SELLGOLDRESP_DEF.containing_type = _SELLGOLDRESP
_OUTGOLDREQ_DEF.containing_type = _OUTGOLDREQ
_OUTGOLDRESP.fields_by_name['result'].message_type = struct_pb2._RESULT
_OUTGOLDRESP_DEF.containing_type = _OUTGOLDRESP
DESCRIPTOR.message_types_by_name['QueryShopReq'] = _QUERYSHOPREQ
DESCRIPTOR.message_types_by_name['QueryShopResp'] = _QUERYSHOPRESP
DESCRIPTOR.message_types_by_name['BuyItemReq'] = _BUYITEMREQ
DESCRIPTOR.message_types_by_name['BuyItemResp'] = _BUYITEMRESP
DESCRIPTOR.message_types_by_name['QueryTradeReq'] = _QUERYTRADEREQ
DESCRIPTOR.message_types_by_name['QueryTradeResp'] = _QUERYTRADERESP
DESCRIPTOR.message_types_by_name['BuyTradeReq'] = _BUYTRADEREQ
DESCRIPTOR.message_types_by_name['BuyTradeResp'] = _BUYTRADERESP
DESCRIPTOR.message_types_by_name['SellGoldReq'] = _SELLGOLDREQ
DESCRIPTOR.message_types_by_name['SellGoldResp'] = _SELLGOLDRESP
DESCRIPTOR.message_types_by_name['OutGoldReq'] = _OUTGOLDREQ
DESCRIPTOR.message_types_by_name['OutGoldResp'] = _OUTGOLDRESP

QueryShopReq = _reflection.GeneratedProtocolMessageType('QueryShopReq', (_message.Message,), dict(
  DESCRIPTOR = _QUERYSHOPREQ,
  __module__ = 'trade_pb2'
  # @@protoc_insertion_point(class_scope:cardgame.QueryShopReq)
  ))
_sym_db.RegisterMessage(QueryShopReq)

QueryShopResp = _reflection.GeneratedProtocolMessageType('QueryShopResp', (_message.Message,), dict(
  DESCRIPTOR = _QUERYSHOPRESP,
  __module__ = 'trade_pb2'
  # @@protoc_insertion_point(class_scope:cardgame.QueryShopResp)
  ))
_sym_db.RegisterMessage(QueryShopResp)

BuyItemReq = _reflection.GeneratedProtocolMessageType('BuyItemReq', (_message.Message,), dict(
  DESCRIPTOR = _BUYITEMREQ,
  __module__ = 'trade_pb2'
  # @@protoc_insertion_point(class_scope:cardgame.BuyItemReq)
  ))
_sym_db.RegisterMessage(BuyItemReq)

BuyItemResp = _reflection.GeneratedProtocolMessageType('BuyItemResp', (_message.Message,), dict(
  DESCRIPTOR = _BUYITEMRESP,
  __module__ = 'trade_pb2'
  # @@protoc_insertion_point(class_scope:cardgame.BuyItemResp)
  ))
_sym_db.RegisterMessage(BuyItemResp)

QueryTradeReq = _reflection.GeneratedProtocolMessageType('QueryTradeReq', (_message.Message,), dict(
  DESCRIPTOR = _QUERYTRADEREQ,
  __module__ = 'trade_pb2'
  # @@protoc_insertion_point(class_scope:cardgame.QueryTradeReq)
  ))
_sym_db.RegisterMessage(QueryTradeReq)

QueryTradeResp = _reflection.GeneratedProtocolMessageType('QueryTradeResp', (_message.Message,), dict(
  DESCRIPTOR = _QUERYTRADERESP,
  __module__ = 'trade_pb2'
  # @@protoc_insertion_point(class_scope:cardgame.QueryTradeResp)
  ))
_sym_db.RegisterMessage(QueryTradeResp)

BuyTradeReq = _reflection.GeneratedProtocolMessageType('BuyTradeReq', (_message.Message,), dict(
  DESCRIPTOR = _BUYTRADEREQ,
  __module__ = 'trade_pb2'
  # @@protoc_insertion_point(class_scope:cardgame.BuyTradeReq)
  ))
_sym_db.RegisterMessage(BuyTradeReq)

BuyTradeResp = _reflection.GeneratedProtocolMessageType('BuyTradeResp', (_message.Message,), dict(
  DESCRIPTOR = _BUYTRADERESP,
  __module__ = 'trade_pb2'
  # @@protoc_insertion_point(class_scope:cardgame.BuyTradeResp)
  ))
_sym_db.RegisterMessage(BuyTradeResp)

SellGoldReq = _reflection.GeneratedProtocolMessageType('SellGoldReq', (_message.Message,), dict(
  DESCRIPTOR = _SELLGOLDREQ,
  __module__ = 'trade_pb2'
  # @@protoc_insertion_point(class_scope:cardgame.SellGoldReq)
  ))
_sym_db.RegisterMessage(SellGoldReq)

SellGoldResp = _reflection.GeneratedProtocolMessageType('SellGoldResp', (_message.Message,), dict(
  DESCRIPTOR = _SELLGOLDRESP,
  __module__ = 'trade_pb2'
  # @@protoc_insertion_point(class_scope:cardgame.SellGoldResp)
  ))
_sym_db.RegisterMessage(SellGoldResp)

OutGoldReq = _reflection.GeneratedProtocolMessageType('OutGoldReq', (_message.Message,), dict(
  DESCRIPTOR = _OUTGOLDREQ,
  __module__ = 'trade_pb2'
  # @@protoc_insertion_point(class_scope:cardgame.OutGoldReq)
  ))
_sym_db.RegisterMessage(OutGoldReq)

OutGoldResp = _reflection.GeneratedProtocolMessageType('OutGoldResp', (_message.Message,), dict(
  DESCRIPTOR = _OUTGOLDRESP,
  __module__ = 'trade_pb2'
  # @@protoc_insertion_point(class_scope:cardgame.OutGoldResp)
  ))
_sym_db.RegisterMessage(OutGoldResp)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\030com.zhili.cardgame.protoB\005TradeH\003'))
# @@protoc_insertion_point(module_scope)
